name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"  # 12시간마다 실행
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: shinleehyeon
          svg_out_path: dist/github-snake-dark.svg
          date_format: YYYY-MM-DD
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
