name: Generate Snake Animation

on:
  # 매일 자정에 실행
  schedule:
    - cron: "0 0 * * *"
  
  # 수동 실행 가능
  workflow_dispatch:
  
  # push할 때마다 실행
  push:
    branches:
      - main
      - master
    
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: shinleehyeon
          outputs: |
            dist/github-snake.svg?color_snake=#4A90E2&color_dots=#F8FAFE,#E3F2FD,#90CAF9,#42A5F5,#1E88E5
            dist/github-snake-dark.svg?color_snake=#64B5F6&color_dots=#0D1117,#1E3A5F,#2196F3,#42A5F5,#64B5F6&palette=github-dark
            
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
