name: Generate Snake Animation

on:
  # 매일 자정에 실행
  schedule:
    - cron: "0 0 * * *"
  
  # 수동 실행 가능
  workflow_dispatch:
  
  # push할 때마다 실행
  push:
    branches:
      - main
      - master
    
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: shinleehyeon
          outputs: |
            dist/github-snake.svg?color_snake=#7CB342&color_dots=#F0F0F0,#C6E48B,#7BC96F,#239A3B,#196127
            dist/github-snake-dark.svg?color_snake=#7CB342&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353&palette=github-dark
            
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
